// Execute the admin module against its actual HTML IDs and lightweight DOM stubs.
const fs=require('fs'),vm=require('vm');
const root=require('path').resolve(__dirname,'..');
const html=fs.readFileSync(root+'/web/admin.html','utf8');
const ids=[...html.matchAll(/id="([^"]+)"/g)].map(m=>m[1]);
const elements=Object.fromEntries(ids.map(id=>[id,{id,value:id==='simChat'?'!km':'3',checked:false,dataset:{},textContent:'',innerHTML:'',style:{},classList:{toggle(){},add(){},remove(){}},querySelectorAll(){return []},append(){}}]));
const actions=[],alerts=[];
const context={console,Set,Math,Date,Number,String,JSON,alert(message){alerts.push(message)},confirm(){return true},setInterval(){return 1},clearInterval(){},window:{open(){}},location:{},qs(selector){const e=elements[selector.slice(1)];if(!e)throw new Error('Missing '+selector);return e},qsa(){return []},fmt(v){return Number(v).toFixed(1)},connect(){},async action(name,payload){actions.push({name,payload});return {reply:'[SIM] 0.0/1000 km'}},fetch:async()=>({json:async()=>({items:[]})})};
const script=html.match(/<script type="module">([\s\S]*?)<\/script>/)[1].replace(/import[^;]+;/,'');
vm.createContext(context);vm.runInContext(script,context);
(async()=>{await elements.simStart.onclick();await elements.simChatSend.onclick();elements.emoteSize.value='96';elements.emoteSpeed.value='70';elements.smallBossTime.value='180';elements.majorBossTime.value='360';await elements.saveBossSettings.onclick();await elements.testBossWarning.onclick();const settings=actions.find(a=>a.name==='config_patch');if(settings?.payload.overlay.emote_size_px!==96||settings?.payload.boss.major_duration_seconds!==360)throw new Error('Settings action failed');if(!actions.some(a=>a.name==='simulation_start')||!actions.some(a=>a.name==='sim_chat'))throw new Error('Action bindings failed');if(!elements.simChatReply.textContent.includes('[SIM]'))throw new Error('Reply output failed');vm.runInContext("renderTwitch({twitch:{authenticated:false,has_token:true,reauth_required:true,last_error:'Bitte erneut anmelden'}})",context);if(elements.twLogin.disabled||elements.twLogout.disabled||!elements.rewardSave.disabled)throw new Error('Invalid auth blocks recovery');vm.runInContext("renderTwitch({twitch:{authenticated:false,has_token:true,validation_pending:true}})",context);if(!elements.oauthCountdown.textContent.includes('prüfe Verbindung'))throw new Error('Pending validation state missing');context.action=async(name)=>{if(name==='twitch_redemptions')throw new Error('ConnectError: Verbindungsfehler');return {}};vm.runInContext("state={twitch:{authenticated:true,connected:true,medipack_reward_id:'reward'}}",context);await vm.runInContext('loadRedemptions()',context);if(alerts.length)throw new Error('Startup redemption error opens popup');if(!elements.redemptions.innerHTML.includes('Medipak-Einlösungen')||!elements.twError.textContent.includes('ConnectError'))throw new Error('Redemption error context missing');console.log('Admin module initialized; startup redemption failure shown inline without popup; simulation and chat buttons bound; local reply displayed.')})().catch(e=>{console.error(e);process.exitCode=1});
