const fs=require('fs'),vm=require('vm'),assert=require('assert');
const html=fs.readFileSync(require('path').resolve(__dirname,'../web/event-overlay.html'),'utf8');
let clock=0;const launched=[],damage=[];
function classes(){const values=new Set();return {add(v){values.add(v)},remove(v){values.delete(v)},contains(v){return values.has(v)},toggle(v,on){if(on)values.add(v);else values.delete(v)}}}
function node(){return {complete:true,naturalWidth:96,style:{},classList:classes(),dataset:{},children:[],_text:'',get textContent(){return this.children.length?this.children.map(x=>x.textContent).join(''):this._text},set textContent(value){this._text=value;this.children=[]},append(e){this.children.push(e)},innerHTML:'',getBoundingClientRect(){return {left:650,top:200,width:200,height:250}},getContext(){return {setTransform(){},clearRect(){},fillRect(){},save(){},restore(){},beginPath(){},moveTo(){},lineTo(){},stroke(){},arc(){},fill(){}}},remove(){this.removed=true},animate(frames,options){launched.push({element:this,frames,options});return {finished:Promise.resolve()}}}}
const elements=Object.fromEntries([...html.matchAll(/id="([^"]+)"/g)].map(m=>[m[1],node()]));
const context={console,Math,Date,Number,String,JSON,Promise,Set,innerWidth:1920,innerHeight:1080,devicePixelRatio:1,performance:{now:()=>clock},requestAnimationFrame(){return 1},addEventListener(){},setTimeout(){return 1},clearTimeout(){},connect(){},fmt(){},qs(selector){if(!elements[selector.slice(1)])throw new Error('Missing '+selector);return elements[selector.slice(1)]},document:{body:{style:{},append(e){if(e.className==='damageNumber')damage.push(e)}},createElement(){return node()}}};
vm.createContext(context);vm.runInContext(html.match(/<script type="module">([\s\S]*?)<\/script>/)[1].replace(/import[^;]+;/,''),context);
const state={features:{},overlay_config:{emote_size_px:96,emote_speed_percent:70},boss:{fight_id:'f1',monster_id:'ember-dragon',monster_name:'Test',boss_type:'small',hp:46,start_hp:47,hp_percent:98,remaining_s:100,participant_count:1,top3:[]},event:null};
context.sampleState=state;context.sampleHit={fight_id:'f1',damage:1,emotes:Array.from({length:10},()=>({code:'Kappa',url:'https://example/kappa.png'}))};
vm.runInContext('renderState(sampleState);projectile(sampleHit)',context);
for(let i=0;i<10;i++){clock=i*200;vm.runInContext('launchSalvos(performance.now())',context)}
const flights=launched.filter(x=>x.element.className==='projectile');assert.equal(flights.length,10);assert.equal(new Set(flights.map(x=>x.element.style.left)).size,1);assert.equal(new Set(flights.map(x=>JSON.stringify(x.frames))).size,1);assert(flights.every(x=>x.element.style.width==='96px'));assert(flights.every(x=>Math.abs(x.options.duration-2000)<1));
Promise.resolve().then(()=>{assert.equal(damage.length,1);assert.equal(damage[0].textContent,'−1');context.sampleState.boss.remaining_s=9;vm.runInContext('renderState(sampleState)',context);assert.equal(elements.timer.textContent,'00:09');assert(elements.timer.classList.contains('critical'));const beforeTick=launched.length;vm.runInContext("setTimerText('00:08')",context);assert.equal(launched.length,beforeTick+1,'Only the changed digit animates');assert.equal(launched.at(-1).element,elements.timer.children[4]);vm.runInContext("setTimerText('00:08')",context);assert.equal(launched.length,beforeTick+1,'Repeated state must not animate again');vm.runInContext("setTimerText('01:00',false)",context);const beforeRollover=launched.length;vm.runInContext("setTimerText('00:59')",context);assert.equal(launched.length,beforeRollover+3,'Minute rollover animates three changed digits');vm.runInContext("showCallout({type:'BOSS_DEFEATED',payload:{monster_name:'Test',participant_count:1}})",context);assert.equal(elements.head.textContent,'MONSTER BESIEGT!');vm.runInContext("handleEvent({type:'BOSS_DEFEATED',payload:{}})",context);assert.equal(elements.timer.textContent,'SIEG!');vm.runInContext("startFinale({created_at:Date.now()/1000})",context);for(let i=0;i<250;i++){clock+=20;vm.runInContext('frame(performance.now())',context)}assert(vm.runInContext('fireParticles.length',context)>0);const originalCreate=context.document.createElement;context.document.createElement=()=>{const e=node();e.complete=false;e.naturalWidth=0;return e};context.sampleHit={fight_id:'f1',damage:1,emotes:[{code:'cold',url:'https://example/cold.png'}]};vm.runInContext('projectile(sampleHit);launchSalvos(performance.now())',context);const count=launched.length;/* No flight before onload. */assert.equal(launched.filter(x=>x.element.className==='projectile').length,10);vm.runInContext('activeProjectiles',context);const pending=[];context.document.body.append=(e)=>pending.push(e);clock+=500;vm.runInContext('projectile(sampleHit);launchSalvos(performance.now())',context);const cold=pending.find(e=>e.className==='projectile');assert(cold);assert.equal(launched.length,count);cold.complete=true;cold.naturalWidth=96;cold.onload();assert.equal(launched.length,count+1);context.document.createElement=originalCreate;console.log('Cold-cache image waits for onload before flight; Salvos, single damage, side clock, only changed digits animate, critical timer, victory message and live fireworks particles verified.');}).catch(e=>{console.error(e);process.exitCode=1});
